blog/urls.py
from django.urls import path
from . import views

app_name = 'blog_app_name'

urlpatterns = [

    path('', views.all_blogs, name="all_blogs"),
    path('<int:blog_id>/', views.detail, name="detail"),

]

personal_portifolio/urls.py
from django.contrib import admin
from django.urls import path
from portfolio import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('blog/', include('blog.urls')),
    path('portfolio/', include('portfolio.urls', namespace="portfolio")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio_app_name'

urlpatterns = [

    path('<int:proj_id>/', views.detail2, name='detail2'),
   
]

    # path('projeto1', views.projeto1, name='projeto1'),
    # path('projeto2', views.projeto2, name='projeto2'),
    # path('projeto3', views.projeto3, name='projeto3'),
    # path('projeto4', views.projeto4, name='projeto4'),

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    date = models.DateField(default=None)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from . models import Blog


def all_blogs(request):
    # pega todos os objetos do banco de dados!
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})


def detail(request, blog_id):

    blog = get_object_or_404(Blog, pk=blog_id)

    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from .models import Project
from django.shortcuts import render, get_object_or_404


def home(request):
    projects = Project.objects.all()     # pega todos os objetos do banco de dados!
    return render(request, 'portfolio/home_backup.html', {'projects': projects})



def detail2(request, proj_id):

    project = get_object_or_404(Project, pk=proj_id)
    if proj_id == 1:
        projeto = 'portfolio/projeto1.html'

    elif proj_id == 2:
        projeto = 'portfolio/projeto2.html'

    elif proj_id == 3:
        projeto = 'portfolio/projeto3.html'

    elif proj_id == 2:
        projeto = 'portfolio/projeto3.html'
  
    return render(request, projeto, {'project': project})

# Projects
# def projeto1(request):
#     return render(request, 'portfolio/projeto1.html')

# def projeto2(request):
#     return render(request, 'portfolio/projeto2.html')

# def projeto3(request):
#     return render(request, 'portfolio/projeto3.html')

# def projeto4(request):
#     return render(request, 'portfolio/projeto4.html')

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}

<h1>Mateus' Blogs (Em breve)</h1>

<h2>Mateus has written {{ blogs.count}} blog{{ blogs.count|pluralize}} </h2>


{% load static %}


<img src="{% static 'portfolio/me1.png' %}" lenght="400" width="300">


<br>
<br>


{% for blog in blogs %}

<a href="{% url 'blog_app_name:detail' blog.id %}">
    <h2>{{ blog.title }}</h2>
</a>

<p>{{ blog.description|safe|truncatechars:100 }}</p>



{% if blog.url %}
<br><a href="{{  blog.url  }}">Link</a>
{% endif %}

<h5>{{ blog.date|date:'M d Y' }}</h5>

{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}

<h1>{{ blog.title }}</h1>

<br>

{{ blog.description|safe }}

<br>

<h2>--{{ blog.date|date:'F jS Y' }}--</h2>

<br>

{{ blog.url }}

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}


<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'portfolio/css_home.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static 'portfolio/Logo.png' %}">
     <link rel="stylesheet" href="{% static 'portfolio/css.base.css' %}">

    <title>Mateus Alves</title>
</head>

<body>

    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static  'portfolio/Logo.png' %}" width="30" height="30" class="d-inline-block align-top"
                    alt="Mateus' logo">
                <span>Mateus Alves</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse text-center" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% static 'portfolio/Resume.pdf' %}" target="_blank">Resume</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.linkedin.com/in/mateus-alves-28608960/"
                            target="_blank">LinkedIn</a>

                    <li>
                        <a role="button" href="{% url 'blog_app_name:all_blogs' %}" class="btn btn-primary"
                            target="_blank">Blog</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

portfolio/templates/portfolio/base_projetos.html
{% load static %}


<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'portfolio/css_home.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static 'portfolio/Logo.png' %}">
     <link rel="stylesheet" href="{% static 'portfolio/css.base.css' %}">

    <title>Mateus Alves</title>
</head>

<body>

    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static  'portfolio/Logo.png' %}" width="30" height="30" class="d-inline-block align-top"
                    alt="Mateus' logo">
                <span>Mateus Alves</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse text-center" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% static 'portfolio/Resume.pdf' %}" target="_blank">Resume</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.linkedin.com/in/mateus-alves-28608960/"
                            target="_blank">LinkedIn</a>

                    <li>
                        <a role="button" href="{% url 'blog_app_name:all_blogs' %}" class="btn btn-primary"
                            target="_blank">Blog</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div>
        {% block content %}{% endblock %}
    </div>

   


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

portfolio/templates/portfolio/detail2.html
{% extends 'portfolio/base.html' %}

{% block content %}



{% load static %}

<h2>About this Project</h2>
<img src="{{ project.image.url }}" class="img-fluid mb-2">



<h2>{{ project.title }}</h2>

<p>{{ project.description|safe }}</p>





{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<h1>Mateus' Portfolio</h1>


<div class="row justify-content-center my-3">
    <div class="col-5">
        <img src="{% static 'portfolio/me1.png' %}" class="img-fluid" lenght="400" width="350">
    </div>
</div>
<br>
<p class="fw-bolder">Hello! I'm Mateus Alves. I am Enonomist, and I am currently working
    as Performance Management Analyst Sr. at Vale mining company in Brazil. Here I am sharing with you some
    Python projects that I have built so far. I hope you'll enjoy it! 😊</p <br>

<h2 class="mt-5">Portfolio</h2>
<br>
<br>



<div class="row">

    <!- Projeto 1 ->
    <div class="col-lg-4 col-md-6">
        <a href="{% url 'portfolio:projeto1' %}">
            <img src="{% static 'portfolio/foto_projeto1.png' %}" class="img-fluid mb-2">
        </a>
        <h3><a href="{% url 'portfolio:projeto1' %}">A Data Analysis Case</a></h3>
        <p>This project presents data analysis tecniques applied to a dataset. This work also shows the importance of data analysis as a valuable tool in the decisiom making
            process.  The technologies utilized for this purpose were Python, Jupyter Notebook,
            Pandas (library) and Matplotlib (library).


            , </p>
    </div>


<!- Projeto 2 ->
     <div class="col-lg-4 col-md-6">
        <a href="{% url 'portfolio:projeto2' %}">
            <img src="{% static 'portfolio/web_scrapping.png' %}" class="img-fluid mb-2">
        </a>
        <h3><a href="{% url 'portfolio:projeto2' %}">Web Scrapping </a></h3>
        <p>Project 2 description</p>
    </div>

<!- Projeto 3 ->
       <div class="col-lg-4 col-md-6">
        <a href="{% url 'portfolio:projeto3' %}">
            <img src="{% static 'portfolio/web_development.png' %}" class="img-fluid mb-2">
        </a>
        <h3><a href="{% url 'portfolio:projeto3' %}">Web Development</a></h3>
        <p>Project 3 description</p>
    </div>
    
    <!- Projeto 4 ->
    <div class="col-lg-4 col-md-6">
       <a href="{% url 'portfolio:projeto4' %}">
           <img src="{% static 'portfolio/web_scrapping.png' %}" class="img-fluid mb-2">
       </a>
       <h3><a href="{% url 'portfolio:projeto4' %}">Web Scrapping </a></h3>
       <p>Project 2 description</p>
   </div>

    


</div>

{% endblock %}

portfolio/templates/portfolio/home_backup.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<h1>Mateus' Portfolio</h1>


<div class="row justify-content-center my-3">
    <div class="col-5">
        <img src="{% static 'portfolio/me1.png' %}" class="img-fluid" lenght="400" width="350">
    </div>
</div>
<br>
<p class="fw-bolder">Hello! I'm Mateus Alves. I am Enonomist, and I am currently working
    as Performance Management Analyst Sr. at Vale mining company in Brazil. Here I am sharing with you some
    Python projects that I have built so far. I hope you'll enjoy it! 😊</p <br>

<h2 class="mt-5">Portfolio</h2>
<br>
<br>



<div class="row">
    {% for project in projects %}
    <div class="col-lg-4 col-md-6">

        {% if project.url %}
        <a href="portfolio/{{ project.id }}">



            <img src="{{ project.image.url }}" class="img-fluid mb-2">
        </a>
        {% else %}

        <img src="{{ project.image.url }}" class="img-fluid mb-2">
        {% endif %}
        <h3><a href="portfolio/{{ project.id }}">{{ project.title }}</a></h3>
        <p>{{ project.description }}</p>
        <p>{{ project.id }}</p>


    </div>
    {% endfor %}
</div>

{% endblock %}

portfolio/templates/portfolio/projeto2.html
{% extends 'portfolio/base_projetos.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Projeto 2 </title>
     <link rel="stylesheet" href="{% static 'portfolio/css_projetos.css' %}">

</head>
<body>


{% block content %}

{% load static %}


<h2>Projeto 2</h2>

<h2>'Data Science'</h2>
<img src="{{ project.image.url }}" class="imag">



<h2>{{ project.title }}</h2>

<p>{{ project.description|safe }}</p>


<div>



    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
        industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
        and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap
        into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release
        of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
        been the industry's standard dummy text ever since the 1500s, when an unknown printer took
        galley of type and scrambled it to make a type specimen book. It has survived not only fi
        ve centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum p
        PageMaker including versions of Lorem Ipsum.
    </p>

    <div class="centro">

        <img src="{% static 'portfolio/print2.PNG' %}" class="corpo" >
    </div>



    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
        industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
        and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap
        into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release
        of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
        been the industry's standard dummy text ever since the 1500s, when an unknown printer took
        a galley of type and scrambled it to make a type specimen book. It has survived not only fi
        ve centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum p
        PageMaker including versions of Lorem Ipsum.
    </p>

    <div class="centro">

        <img src="{% static 'portfolio/print.PNG' %}" class="corpo" >
    </div>


    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
        industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
        and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap
        into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release
        of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
        been the industry's standard dummy text ever since the 1500s, when an unknown printer took
        a galley of type and scrambled it to make a type specimen book. It has survived not only fi
        ve centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum p
        PageMaker including versions of Lorem Ipsum.
    </p>

    <div class="centro">
        <img src="{% static 'portfolio/print.PNG' %}" class="corpo" >



    {% endblock %}

</div>

</body>
</html>

portfolio/templates/portfolio/projeto3.html
{% extends 'portfolio/base_projetos.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Projeto 1 </title>
     <link rel="stylesheet" href="{% static 'portfolio/css_projetos.css' %}">
     
</head>
<body>


{% block content %}

{% load static %}


<h2>Projeto 3</h2>

<h2>'Data Science'</h2>
<img src="{{ project.image.url }}" class="imag">



<h2>{{ project.title }}</h2>

<p>{{ project.description|safe }}</p>


<div>

    
    
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
        industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
        and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap
        into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release
        of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
        been the industry's standard dummy text ever since the 1500s, when an unknown printer took
        galley of type and scrambled it to make a type specimen book. It has survived not only fi
        ve centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum p
        PageMaker including versions of Lorem Ipsum.
    </p>
    
    <div class="centro">
    
        <img src="{% static 'portfolio/print2.PNG' %}" class="corpo" >
    </div>
    
    
    
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
        industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
        and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap
        into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release
        of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
        been the industry's standard dummy text ever since the 1500s, when an unknown printer took
        a galley of type and scrambled it to make a type specimen book. It has survived not only fi
        ve centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum p
        PageMaker including versions of Lorem Ipsum.
    </p>
    
    <div class="centro">
    
        <img src="{% static 'portfolio/print.PNG' %}" class="corpo" >
    </div>
            
    
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
        industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
        and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap
        into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release
        of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
        been the industry's standard dummy text ever since the 1500s, when an unknown printer took
        a galley of type and scrambled it to make a type specimen book. It has survived not only fi
        ve centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum p
        PageMaker including versions of Lorem Ipsum.
    </p>

    <div class="centro">
        <img src="{% static 'portfolio/print.PNG' %}" class="corpo" >
    
    

    {% endblock %}

</div>

</body>
</html>

portfolio/templates/portfolio/projeto4.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Projeto 1 </title>
     <link rel="stylesheet" href="{% static 'portfolio/css_projetos.css' %}">
</head>
<body>
<h1>Projeto 3</h1>
<h2>Introdução</h2>

<div>

         <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
        industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
        and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap
        into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release
        of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
         been the industry's standard dummy text ever since the 1500s, when an unknown printer took
        a galley of type and scrambled it to make a type specimen book. It has survived not only fi
        ve centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum p
        PageMaker including versions of Lorem Ipsum.</p>

        <div class="container">

            <img src="{% static 'portfolio/print2.PNG' %}" class="img" >
        </div>



    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
        industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
        and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap
        into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release
        of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
         been the industry's standard dummy text ever since the 1500s, when an unknown printer took
        a galley of type and scrambled it to make a type specimen book. It has survived not only fi
        ve centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum p
        PageMaker including versions of Lorem Ipsum.</p>

    <img src="{% static 'portfolio/print.PNG' %}" class="img" >

    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
        industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
        and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap
        into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release
        of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
         been the industry's standard dummy text ever since the 1500s, when an unknown printer took
        a galley of type and scrambled it to make a type specimen book. It has survived not only fi
        ve centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum p
        PageMaker including versions of Lorem Ipsum.</p>

    <img src="{% static 'portfolio/print.PNG' %}" class="img" >




</div>

</body>
</html>